apiVersion: v1
kind: Pod
metadata:
  name: set2-source
spec:
  containers:
    - name: source
      image: SOURCE_IMAGE
      command:
        - tail
        - -f
        - /dev/null
  nodeSelector:
    kubernetes.io/hostname: SOURCE_NODE

---
apiVersion: v1
kind: Service
metadata:
  name: set2-sink-svc1
spec:
  clusterIP: None
  ports:
    - name: "dummy"
      port: 8080
  selector:
    type: set2-sink-depl1-pods

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: set2-sink-depl1
  labels:
    type: set2-sink-depl1
spec:
  replicas: 2
  selector:
    matchLabels:
      type: set2-sink-depl1-pods
  template:
    metadata:
      labels:
        type: set2-sink-depl1-pods
    spec:
      containers:
        - name: sink
          image: busybox:latest
          command:
            - tail
            - -f
            - /dev/null
      nodeSelector:
        kubernetes.io/hostname: SINK_NODE
      
---
apiVersion: v1
kind: Service
metadata:
  name: set2-sink-svc2
spec:
  ports:
    - name: "dummy"
      port: 8080
  selector:
    type: set2-sink-depl2-pods

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: set2-sink-depl2
  labels:
    type: set2-sink-depl2
spec:
  replicas: 2
  selector:
    matchLabels:
      type: set2-sink-depl2-pods
  template:
    metadata:
      labels:
        type: set2-sink-depl2-pods
    spec:
      containers:
        - name: sink
          image: busybox:latest
          command:
            - tail
            - -f
            - /dev/null
      nodeSelector:
        kubernetes.io/hostname: SINK_NODE
      
